# Generated by Django 4.1.4 on 2022-12-16 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_isbn_book_launch'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15, verbose_name='Usuário')),
                ('firstname', models.CharField(max_length=200, verbose_name='Nome')),
                ('secondname', models.CharField(max_length=200, verbose_name='Sobrenome')),
                ('email', models.CharField(max_length=200, verbose_name='Email')),
                ('cell_number', models.CharField(max_length=12, verbose_name='Local')),
                ('password', models.CharField(max_length=12, verbose_name='Senha')),
                ('birth', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Quantidade')),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='Livro')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.user', verbose_name='Usuário')),
            ],
        ),
    ]
