# Generated by Django 4.1.4 on 2022-12-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_user_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birth',
        ),
        migrations.AlterField(
            model_name='user',
            name='cell_number',
            field=models.CharField(max_length=12, verbose_name='Telefone'),
        ),
    ]
