# Generated by Django 4.1.4 on 2022-12-20 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_remove_user_birth_alter_user_cell_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=255, null=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cell_number',
            field=models.CharField(max_length=12, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='firstname',
            field=models.CharField(max_length=200, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='user',
            name='secondname',
            field=models.CharField(max_length=200, null=True, verbose_name='Sobrenome'),
        ),
    ]
