# Generated by Django 4.1.4 on 2022-12-26 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_user_address_alter_user_cell_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(to='books.author', verbose_name='Autores'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='book',
            name='launch',
            field=models.DateField(blank=True, null=True, verbose_name='Lançamento'),
        ),
    ]
